[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nomadplayer"
version = "0.1.0"
description = "Lecteur musical minimaliste pour terminal"
requires-python = ">=3.9"

[project.scripts]
Nplayer = "NomadPlayer.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
